/**
 * HarnessWiki City — TypeScript MIRROR of the canonical contracts.
 *
 * CANONICAL SOURCE: `harness/contracts.py` (Pydantic). This file is a hand-kept
 * mirror so the dashboard has types; regenerate it from `contracts.py` and keep
 * `docs/DATA_CONTRACTS.md` in sync in the same change (AGENTS.md #1).
 *
 * SUPERSET MERGE (DECISIONS.md D8): the "core" fields are render-ready and used
 * by the dashboard today. Fields marked "Eng 1 additions" are optional — the
 * Python side serializes with exclude_none, so a None is simply absent here.
 * `data/stubs/*.json` are generated by `scripts/dump_stubs.py` and validated
 * against these types by `_stub-check.ts` (the cross-language consistency check).
 */

export type TrendSignal = {
  label: string;
  strength: number; // 0..1
  note?: string;
};

export type TrendContext = {
  // core (render-ready)
  id: string;
  captured_at: string; // ISO-8601
  platform: string; // "tiktok" | "x" | "linkedin" | ...
  audience: string;
  trend_summary: string;
  signals: TrendSignal[];
  source: "stub" | "live";
  // Eng 1 additions (optional)
  trend_id?: string; // ≡ id
  topic?: string;
  hook?: string;
  format?: string;
  audio?: string;
  region?: string;
  source_urls?: string[];
  raw_signals?: Record<string, unknown>;
};

// The chosen sound for a short-form concept. Distinct from TrendContext.audio
// (which just names a sound the trend is using).
export type Audio = {
  name?: string;
  bpm?: number;
  sound_recency?: string; // "new" | "rising" | "established"
  is_rising_sound?: boolean;
};

// platform/execution details, separated from the creative idea (ACOE v2)
export type ExecutionMetadata = {
  hashtag_set?: string[];
  posting_time?: string; // ISO-8601
};

export type ContentConcept = {
  // core (render-ready)
  id: string;
  generation_number: number;
  trend_context_id: string;
  harness_state_version: string;
  hook: string;
  format: string; // a key into HarnessState.element_weights
  angle: string;
  script: string;
  visual_prompt: string;
  elements: string[]; // element tags used
  created_by: string;
  // Eng 1 additions (optional)
  concept_id?: string; // ≡ id
  generation?: number; // ≡ generation_number
  trend_id?: string; // ≡ trend_context_id
  element_weights?: Record<string, number>; // inner-loop policy snapshot
  storyboard?: string[];
  seedance_prompt?: string; // ≡ visual_prompt
  duration_sec?: number; // ≡ length
  created_at?: string;
  // short-form-video attributes (Eng 1's TikTok feature set; optional)
  dance_style?: string;
  audio?: Audio;
  cut_frequency?: number; // cuts per second (scored by ACOE v2 VP-04)
  execution?: ExecutionMetadata; // platform/execution details (ACOE v2)
  hashtag_set?: string[]; // deprecated (ACOE v2) — use execution.hashtag_set
  posting_time?: string; // deprecated (ACOE v2) — use execution.posting_time
  // ACOE Shorts generation attributes (optional)
  comment_bait_question?: string;
  on_screen_text?: string;
  title?: string;
  description?: string;
};

export type RewardScore = {
  // core (render-ready)
  id: string;
  concept_id: string;
  generation_number: number;
  harness_state_version: string;
  weighted_total: number; // aggregate 0..1 reward — the stable scalar target
  predicted_win_prob?: number; // pairwise win prob vs baseline, 0..1
  policy_flag: boolean;
  judge_rationale: string;
  // Eng 1 additions (optional)
  predicted_score?: number; // ≡ normalized weighted_total
  pairwise_winprob?: number; // ≡ predicted_win_prob
  confidence?: number;
  scored_by?: string;
  rationale?: string; // ≡ judge_rationale
  scored_at?: string;
  // ACOE-YT-SHORTS-v1.0 outputs (additive — see DECISIONS.md D11)
  total_score?: number; // 0–100
  distribution_tier?: string; // "viral" | "growing" | "seed_jail"
  auto_fails_triggered?: string[];
  category_breakdown?: Record<string, number>;
  lowest_scoring_category?: string;
  recommended_fix_priority?: string;
  // critic learning signal (optional; consumed by the inner loop) — PR #2
  winning_elements?: string[];
  weak_elements?: string[];
  suggested_policy_updates?: Record<string, number>;
  rubric_breakdown?: Record<string, unknown>;
  // score provenance (Stage 1 / D17)
  score_type?: "projected" | "verified" | "partial";
  evidence_coverage?: number;
};

export type HarnessState = {
  // core (render-ready)
  id: string;
  version: string;
  element_weights: Record<string, number>;
  script_prompt: string;
  seedance_prompt_template: string;
  judge_rubric: string;
  policy_rules: string[];
  updated_from_generation_id?: string;
  // Eng 1 additions (scaffold + lineage; optional)
  generation?: number;
  system_prompt?: string; // ≡ script_prompt
  tools?: string[];
  element_taxonomy?: string[]; // the action space the meta-agent can expand
  few_shot_examples?: Record<string, unknown>[];
  rubric_version?: string;
  parent_harness_id?: string;
  diff_summary?: string;
};

export type HarnessDiff = {
  id: string;
  from_version: string;
  to_version: string;
  element_weight_changes: Record<string, number>; // deltas
  script_prompt_change?: string;
  seedance_prompt_template_change?: string;
  judge_rubric_change?: string;
  policy_rule_changes?: string[];
  rationale: string;
  accepted: boolean;
};

export type Lesson = {
  id: string;
  generation_number: number;
  observation: string;
  rule: string;
  evidence: string;
  harness_change: string;
  expected_effect: string;
};

// real-world result of a posted concept — ground truth (D17). None until posted + collected.
// avg_percent_viewed (APV) is the Shorts loop metric.
export type Outcome = {
  collected_at: string; // ISO-8601
  maturity_hours?: number;
  platform: string; // "youtube_shorts"
  source: string; // "youtube_api" | "manual" | "synthetic" | "stub"
  impressions?: number;
  views?: number;
  avg_percent_viewed?: number; // APV (0..1+); >1 = rewatch loops
  likes?: number;
  comments?: number;
  shares?: number;
  follows?: number;
  retention_curve?: number[];
};

// one of the N concepts considered in a generation — the contrastive batch (D17)
export type Candidate = {
  variant_id: string;
  concept: ContentConcept;
  score: RewardScore;
  selected?: boolean;
  exploration?: boolean;
  outcome?: Outcome;
};

export type GenerationRecord = {
  // core (render-ready — embeds concept + score so the dashboard needs no joins)
  id: string;
  generation_number: number;
  created_at: string;
  trend_context_id: string;
  concept: ContentConcept;
  score: RewardScore;
  harness_state_version_before: string;
  harness_state_version_after?: string;
  harness_diff?: HarnessDiff;
  lesson?: Lesson;
  // Eng 1 additions (lean refs + posting; optional)
  record_id?: string; // ≡ id
  generation?: number; // ≡ generation_number
  trend_id?: string; // ≡ trend_context_id
  concept_id?: string; // ≡ concept.id
  harness_id?: string;
  predicted_score?: number; // ≡ score.weighted_total
  actual_engagement?: Record<string, number>; // @deprecated (D17) — use `outcome`
  outcome?: Outcome; // typed ground truth; populated after posting
  candidates?: Candidate[]; // the full per-generation batch (contrastive signal, D17)
  rubric_version?: string;
  diff_summary?: string;
  selected?: boolean;
  post_url?: string;
};
